### ISSUE TITLE
Serve boot image and vbmeta on UBports CD Image server

### ISSUE THREAD

**Issue by SevralT** [ubports/installer-configs#127]
@Flohack74 Hello! Can you please upload boot and vbmeta images to cd image server [from my gitlab repo](https://gitlab.com/SevralT/ubports-oneplus6/-/tree/master/)?

**Comment by Flohack74** [comment]
Whats your actual codename for 6?

**Comment by Flohack74** [comment]
Forget it here you are: https://cdimage.ubports.com/devices/enchilada_fajita/

**Comment by SevralT** [comment]
> Forget it here you are: https://cdimage.ubports.com/devices/enchilada_fajita/

Thanks :)
