### ISSUE TITLE
Investigate fastboot reboot recovery

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/installer-configs#134]
Fixed. On related note, there currently seems to be no way to reboot from fastboot to recovery? (`fastboot reboot recovery` command)

_Originally posted by @NotKit in https://github.com/ubports/installer-configs/pull/133#discussion_r717350279_

**Comment by amartinz** [comment]
Installer side: https://github.com/ubports/ubports-installer/pull/2492

Config side: https://github.com/ubports/installer-configs/pull/169
