### ISSUE TITLE
Contributing config file for moto g5

### ISSUE THREAD

**Issue by Ritvik-Sapra** [ubports/installer-configs#67]
I have a moto g5 phone (**not moto g5+**). It has 3 GB RAM, 16 GB internal memory, has android 8.1.0 running on it, and Snapdragon 430. I was looking to run Ubuntu Touch on it, when I came to [this site](https://devices.ubuntu-touch.io/device/titan/). I would love to contribute and was looking for guidance on how to do so. Maybe the community can help.

**Comment by NeoTheThird** [comment]
Hey, thank you for your interest in contributing. Is the Moto g5 the same as the Moto G 2014? If it is, you should be able to write a config. Check out the configs for other devices in this repository, they are `YAML` files in `/v2/devices/<codename>.yml`. You can base a new file for this device. If not, you'll have to look into creating a port first, go to https://docs.halium.org for further information.
